name: Daily Facebook Post

on:
  schedule:
  - cron: '0 16 * * *'
  workflow_dispatch:

jobs:
  run-daily-facebook-post:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      META_ACCESS_TOKEN: ${{ secrets.META_ACCESS_TOKEN }}
      FB_PAGE_ID: ${{ secrets.FB_PAGE_ID }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run Daily Facebook Bot
        run: python src/facebook_bot/daily_facebook_post.py
