name: Social Media Automation

on:
  schedule:
    # Run every 8 hours (3 times a day)
    - cron: '0 */8 * * *'
  workflow_dispatch:

jobs:
  run-bots:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
      TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
      TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
      TWITTER_ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_SECRET }}
      META_ACCESS_TOKEN: ${{ secrets.META_ACCESS_TOKEN }}
      # IG_BUSINESS_ID: ${{ secrets.IG_BUSINESS_ID }}
      TIKTOK_ACCESS_TOKEN: ${{ secrets.TIKTOK_ACCESS_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$GITHUB_WORKSPACE" >> $GITHUB_ENV
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Schedule AI Posts
        run: python src/post_scheduler.py
      - name: Run Twitter Reply Bot
        run: python src/twitter_bot/reply_mentions.py
      # - name: Run Instagram Reply Bot
      #   run: python src/instagram_bot/instagram_replies.py
      - name: Run Facebook Reply Bot
        run: python src/facebook_bot/reply_comments.py
      - name: Generate Video and Post to TikTok
        run: python src/video_bot/tiktok_video_bot.py
